### ISSUE TITLE
New inventory loaded from Hikari: .QUEST_BOOK

### ISSUE THREAD

**Issue by BrokenKage** [peacefulcraft-network/SwordCraftOnline#115]
Need backend support for new inventory type Quest_Book. This will hold single paper items with display name and lore modified to show basic quest information.

**Comment by Parsonswy** [comment]
I forgot that one of the limitations of the existing inventory system was that it can only save items of type `SwordSkillIdentifier` which won't work here. That's something that I've slated to fix with new inventories. I will try to fast track that and have it done in the next 10 days.

**Comment by Parsonswy** [comment]
Need store
1. Name of quest
2. Type of quest (Quest.QuestStep)
3. step
4. ExtraData
