### ISSUE TITLE
Weapon equips

### ISSUE THREAD

**Issue by BrokenKage** [peacefulcraft-network/SwordCraftOnline#143]
Expansion of new inventory merge for weapons.

- [x] Detect when an official weapon is in players hand. ( See Damage or Interact Event )
- [x] Detect players equipped main weapon. Previously discussed we lock the hot bar to one weapon.
- [x] Add "roll" feature for getting extra effects on weapons above X tier.
- [x] Parse lore data for extra effects on equip.
- [x] Limit weapon types in player inventory hotbar

**Comment by BrokenKage** [comment]
@Parsonswy We originally discussed locking the players hotbar items to only contain one weapon. Is this still the plan? This will influence how extra stat effects and modifiers are handled with the weapons.

**Comment by Parsonswy** [comment]
I think it makes sense. Being able to quick switch weapons during combat is not very realistic. Maybe we compromise and restrict it by weapon type so you could at most have a sword, knife, and ranged weapon (bow/crossbow).

Not sure if we planned on adding the legendary 'dual wielding' ability.

**Comment by BrokenKage** [comment]
Original plan was slots 0, 1, 2 be Primary, Sword, Secondary skills respectively. However, I am not sure if that has changed in recent months.
I think limiting weapons as you said would be most user friendly. This could be achieved with Inventory Listeners and Item Pickup Listeners:
- In event an item is placed in hotbar we check an NBT tag for weapon type. If it exceeds allowed weapons we cancel.
- In event an item is picked up we check NBT tag and place in inventory or hotbar respectively.

This way all secondary effects on the weapons can be registered and effect the player generally as opposed to only when the weapon is equipped in hand. I.e. A sword with +0.2 Armor changes the armor stat as long as it is in hotbar.
