### ISSUE TITLE
SwordSkillInventory not loading on relog

### ISSUE THREAD

**Issue by BrokenKage** [peacefulcraft-network/SwordCraftOnline#161]
On reload all sword skills in top slots are not loaded from SQL. Bug occurs on Combat-Inventory branch for sword skill testing.

Skills remain in inventory until player relogs.

**Comment by Parsonswy** [comment]
@BrokenKage On relog or reload? Are there any errors in the console and have you noticed this with any specific sword skills being equiped?

If it is reload the answer is the system was not written to support reloading. To support reloading in the plugin as a whole we would need to implement a Towny-style lockdown system with a companion plugin to prevent people from modifying anything while the plugin was reloading. Without that we would run into a bunch of duplication issues for anything involving an inventory, as well as lapses in region protections that are backed by SCO.

**Comment by BrokenKage** [comment]
@Parsonswy To clarify, the issue is with logging in to the server in general. No skills are loaded and nothing is logged in console.

**Comment by Parsonswy** [comment]
I think when I created [`BukkitInventoryBase.generateItemIdentifiers()`](https://github.com/peacefulcraft-network/SwordCraftOnline/commit/53f626845ae78fc68710282f23850b4a6e55fc12#diff-74455a4298aa1ffd77eaa2edc59f486a5d503b7d11b0f227c1299d50ad3071d0L46), I consolidated some stuff and just forgot to add in a call to that method in [`SwordSkillInventory`](https://github.com/peacefulcraft-network/SwordCraftOnline/commit/53f626845ae78fc68710282f23850b4a6e55fc12#diff-74455a4298aa1ffd77eaa2edc59f486a5d503b7d11b0f227c1299d50ad3071d0L46).

**Comment by Parsonswy** [comment]
@BrokenKage I think it will ping you, but if it doesn't here is a ping saying this is fixed on this branch. Move it around as you need.
