### ISSUE TITLE
Null pointer on inventory open with tome item.

### ISSUE THREAD

**Issue by BrokenKage** [peacefulcraft-network/SwordCraftOnline#25]
Null pointer line 59 Inventory Actions in branch inventory_merge_swordskill_refactor. Unsure if deprecated branch or bug.

**Comment by Parsonswy** [comment]
Happens when player's inventory is null. Offending line was ~50 in LoadPlayerInventory. If the player had no items the task would terminate instead of creating an empty inventory. This has been corrected.
