### ISSUE TITLE
GameManager.joinGame throws null pointer when attempting to teleport to waystone location

### ISSUE THREAD

**Issue by Parsonswy** [peacefulcraft-network/SwordCraftOnline#28]
There are no waystone locations configured in the config right now so Spigot freaks out when you try to teleport to null location.

https://github.com/peacefulcraft-network/SwordCraftOnline/blob/master/src/net/peacefulcraft/sco/gamehandle/GameManager.java#L35

I've commented the line out for now as it breaks the entire join game / inventory load sequence since it all fires off the same event.

**Comment by BrokenKage** [comment]
Added catch that sends player to spawn if their stored floor waystone is not configured correctly.
