### ISSUE TITLE
Break swordskills into primary and secondary trigger items

### ISSUE THREAD

**Issue by Parsonswy** [peacefulcraft-network/SwordCraftOnline#48]

**Comment by Parsonswy** [comment]
@BrokenKage We decided that primary the ones you click to active and secondary was passive, right?

```java
package net.peacefulcraft.sco.swordskills;

public enum SwordSkillType {
  SWORD, PRIMARY, SECONDARY, PASSIVE
}
```
Is what the enum looks like right now which is confusing.

**Comment by BrokenKage** [comment]
@Parsonswy 
SWORD: Skills equipped to their weapon in hand
PRIMARY: Skills equipped to the primary trigger item
SECONDARY: Skills equipped to secondary trigger item
PASSIVE: All other skills that modify player effects on equip. Increasing/decreasing combat stats, Setting potion effects, etc

Original discussion was breaking sword, primary, secondary skills into these “triggers” by the level of effect of the skills. Sword triggers being more combat focused. Primary’s being more grandiose effects. Secondary’s being lesser grandiose.

**Comment by Parsonswy** [comment]
So the activations are;
- **SWORD**: Activated with right click of sword
- **Primary**: Activated by right clicking with item in hotbar?
- **Secondary**: Activated by right clicking with item in hotbar?

@BrokenKage

**Comment by BrokenKage** [comment]
Yes, although the sword activations should also be safe to trigger with any combat item, such as an axe. Not sure how this will interact with our custom textures however.
@Parsonswy

**Comment by Parsonswy** [comment]
@BrokenKage
The custom models shouldn't impact anything. It will still be an axe, just with an extra NBT flag. 
I still think we could simplify the types, both for our sake when when making them, and the users sake that have to learn the difference between them to play the game.
Would something like;
- **Primary**: Triggers by right click with weapon
- **Secondary**: Triggers by right click with item
- **Passive**: Passive.

Saying 'Sword Sword Skill' sounds like a typo and I think if we want to differentiate by how grandiose the skill is, we could give it a higher item tier.
