### ISSUE TITLE
Inventory not writing to memory correctly

### ISSUE THREAD

**Issue by BrokenKage** [peacefulcraft-network/SwordCraftOnline#7]
Inventory saver is either not writing meta data, or not loading correctly. Items are being loaded even after being removed from inventory. I.e. No-meta flint being removed from inventory on multiple occasions and still being loaded in on inventory open.

**Comment by Parsonswy** [comment]
Save inventory contents on close; 2982e9b772183301799c267316462bf024312b84.

**Comment by Parsonswy** [comment]
Serialize and restore display names and lore; 01628f844314b5b00064cbd69529bffd34fd6180
