### ISSUE TITLE
SwordSkill Unregister not triggering on item move event.

### ISSUE THREAD

**Issue by BrokenKage** [peacefulcraft-network/SwordCraftOnline#89]
Unregister is not triggering on item move. Causing SCOPlayer data changing skills to not change data values back to original state.

i.e. Placing a Attack Damage 1.2x, closing and opening inventory, moving it one slot over, and closing again. This causes the damage value to be multiplied by 1.2x twice without going back to base.

**Comment by Parsonswy** [comment]
Pending merge. Closed by https://github.com/peacefulcraft-network/SwordCraftOnline/commit/b660275302339b16356f666b0cfe56504435d629
